package org.usfirst.frc3925.Maurice.subsystems;

import org.usfirst.frc3925.Maurice.RobotMap;
import org.usfirst.frc3925.Maurice.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Drive extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    SpeedController leftFront = RobotMap.driveLeftFront;
    SpeedController leftBack = RobotMap.driveLeftBack;
    SpeedController rightFront = RobotMap.driveRightFront;
    SpeedController rightBack = RobotMap.driveRightBack;
    RobotDrive drive = RobotMap.drivedrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DefaultDrive());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void arcade(double fwd, double turn) {
        drive.arcadeDrive(fwd, turn);
    }
}
