package org.usfirst.frc3925.Maurice.subsystems;

import org.usfirst.frc3925.Maurice.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

public class FeederArm extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    DoubleSolenoid armsolenoid = RobotMap.feederArmarmsolenoid;
    Compressor compressor = RobotMap.feederArmcompressor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private boolean isdown;
    public static final byte FWD = 1, BACK = -1, OFF = 0;

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }

    public void set(byte dir) {
        switch (dir) {
            case FWD:
                armsolenoid.set(DoubleSolenoid.Value.kForward);
                isdown = true;
                break;
            case BACK:
                armsolenoid.set(DoubleSolenoid.Value.kReverse);
                isdown = false;
                break;
            default:
                armsolenoid.set(DoubleSolenoid.Value.kOff);
        }
    }
    
    public boolean isdown() {
        return isdown;
    }
}
