package org.usfirst.frc3925.Maurice.subsystems;

import org.usfirst.frc3925.Maurice.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

public class Winch extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController winchTalon = RobotMap.winchWinchtalon;
    DigitalInput winchSwitch = RobotMap.winchwinchswitch;
    // END AUTOGENERATED CODE, SOURCE=ROBObUILDER ID=DECLARATIONS

    public void set(double speed) {
        winchTalon.set(speed);

    }

    public boolean get() {
        return winchSwitch.get();
    }

    public void initDefaultCommand() {

    }
}
