package org.usfirst.frc3925.Maurice.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3925.Maurice.Robot;
import org.usfirst.frc3925.Maurice.subsystems.FeederArm;

public class FeederDown extends Command {

    public FeederDown() {

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.feederArm);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time

    protected void initialize() {
    }

    protected void execute() {
        Robot.feederArm.set(FeederArm.FWD);
    }

    protected boolean isFinished() {
        return true;
    }

    protected void end() {
    }

    protected void interrupted() {
    }
}
