package org.usfirst.frc3925.Maurice.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3925.Maurice.Robot;

public class WinchBack extends Command {

    private Timer timer;
    private boolean haspulled;

    public WinchBack() {
        
        timer = new Timer();

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.winch);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    }

    protected void initialize() {
        timer.stop();
        timer.reset();
        haspulled = false;
    }

    protected void execute() {

        if (!Robot.winch.get()) {
            Robot.winch.set(1);
        } else {
            if (!haspulled) {
                haspulled = true;
                timer.start();
                timer.reset();
            }
            Robot.winch.set(-.5);
        }

    }

    protected boolean isFinished() {
        return timer.get() >= 2;
    }

    protected void end() {
    }

    protected void interrupted() {
    }
}
